In [ ]:
import kagglehub

path = kagglehub.dataset_download("guimacrlh/dataset-vendas")
print("Path to dataset files:", path)

C:\Users\hamms\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading from https://www.kaggle.com/api/v1/datasets/download/guimacrlh/dataset-vendas?dataset_version_number=2...

100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 971k/971k [00:00<00:00, 1.26MB/s]

Extracting files...
Path to dataset files: C:\Users\hamms\.cache\kagglehub\datasets\guimacrlh\dataset-vendas\versions\2

In [19]:
import pandas as pd
import os
import datetime

path = r"C:\Users\hamms\.cache\kagglehub\datasets\guimacrlh\dataset-vendas\versions\2"

print(os.listdir(path))

['Avaliacoes.csv', 'Campanhas.csv', 'Clientes.csv', 'Colaboradores.csv', 'Custos_Operacionais.csv', 'Devolucoes.csv', 'Fornecedores.csv', 'Historico_Vendas.csv', 'Lojas.csv', 'Pedidos_Compra.csv', 'Produtos.csv', 'Satisfacao.csv', 'Stock.csv', 'Vendas.csv']

In [20]:
arquivos = ['Historico_Vendas.csv', 'Lojas.csv', 'Produtos.csv']
for arquivo in arquivos:
    print(f"\n{'='*50}\n Analisando: {arquivo}\n{'='*50}")
    df = pd.read_csv(os.path.join(path, arquivo))

    print("\n Info geral:")
    print(df.info())

    print("\n Tipos de dados:")
    print(df.dtypes)

    print("\n Primeiras linhas:")
    print(df.head())

    print("\n Valores nulos por coluna:")
    print(df.isnull().sum())

    print("\n Strings vazias por coluna:")
    print((df == '').sum())

    print("\n Registros duplicados:", df.duplicated().sum())

    print("\n Valores √∫nicos por coluna:")
    print(df.nunique())

    print("\nüìä Estat√≠sticas descritivas:")
    print(df.describe(include='all'))

==================================================
 Analisando: Historico_Vendas.csv
==================================================

 Info geral:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Venda_ID        10000 non-null  int64
 1   Loja_ID         10000 non-null  int64
 2   Produto_ID      10000 non-null  int64
 3   Cliente_ID      10000 non-null  int64
 4   Colaborador_ID  10000 non-null  int64
 5   Quantidade      10000 non-null  int64
 6   Pre√ßo Unit√°rio  10000 non-null  float64
 7   Data da Venda   10000 non-null  object
 8   Canal de Venda  10000 non-null  object
dtypes: float64(1), int64(6), object(2)
memory usage: 703.3+ KB
None

 Tipos de dados:
Venda_ID            int64
Loja_ID             int64
Produto_ID          int64
Cliente_ID          int64
Colaborador_ID      int64
Quantidade          int64
Pre√ßo Unit√°rio    float64
Data da Venda      object
Canal de Venda     object
dtype: object

 Primeiras linhas:
   Venda_ID  Loja_ID  Produto_ID  Cliente_ID  Colaborador_ID  Quantidade  \
0         1        5         775          24             338          81
1         2        1         401         425             298          54
2         3        4         903         291              68          18
3         4        2         158         814               8          14
4         5        5         105         631             110          51

   Pre√ßo Unit√°rio        Data da Venda Canal de Venda
0          180.26  2020-02-14 14:46:54         F√≠sica
1          104.39  2016-01-29 19:59:41         F√≠sica
2          952.40  2021-12-19 20:02:31         Online
3          340.92  2014-11-24 10:51:46         Online
4          865.68  2015-05-17 11:33:03         Online

 Valores nulos por coluna:
Venda_ID          0
Loja_ID           0
Produto_ID        0
Cliente_ID        0
Colaborador_ID    0
Quantidade        0
Pre√ßo Unit√°rio    0
Data da Venda     0
Canal de Venda    0
dtype: int64

 Strings vazias por coluna:
Venda_ID          0
Loja_ID           0
Produto_ID        0
Cliente_ID        0
Colaborador_ID    0
Quantidade        0
Pre√ßo Unit√°rio    0
Data da Venda     0
Canal de Venda    0
dtype: int64

 Registros duplicados: 0

 Valores √∫nicos por coluna:
Venda_ID          10000
Loja_ID               5
Produto_ID         1000
Cliente_ID         1000
Colaborador_ID      500
Quantidade          100
Pre√ßo Unit√°rio     9535
Data da Venda      9999
Canal de Venda        2
dtype: int64

üìä Estat√≠sticas descritivas:
           Venda_ID       Loja_ID    Produto_ID    Cliente_ID  Colaborador_ID  \
count   10000.00000  10000.000000  10000.000000  10000.000000    10000.000000
unique          NaN           NaN           NaN           NaN             NaN
top             NaN           NaN           NaN           NaN             NaN
freq            NaN           NaN           NaN           NaN             NaN
mean     5000.50000      2.993200    501.369100    499.418900      247.814300
std      2886.89568      1.415823    288.808457    288.473873      143.933598
min         1.00000      1.000000      1.000000      1.000000        1.000000
25%      2500.75000      2.000000    253.000000    249.000000      123.000000
50%      5000.50000      3.000000    498.000000    497.000000      249.000000
75%      7500.25000      4.000000    754.000000    753.000000      369.000000
max     10000.00000      5.000000   1000.000000   1000.000000      500.000000

          Quantidade  Pre√ßo Unit√°rio        Data da Venda Canal de Venda
count   10000.000000    10000.000000                10000          10000
unique           NaN             NaN                 9999              2
top              NaN             NaN  2014-07-22 16:55:39         F√≠sica
freq             NaN             NaN                    2           5006
mean       50.468500      498.779811                  NaN            NaN
std        28.844351      289.817112                  NaN            NaN
min         1.000000        2.050000                  NaN            NaN
25%        26.000000      246.032500                  NaN            NaN
50%        50.000000      500.150000                  NaN            NaN
75%        76.000000      750.055000                  NaN            NaN
max       100.000000      999.670000                  NaN            NaN

==================================================
 Analisando: Lojas.csv
==================================================

 Info geral:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Loja_ID  5 non-null      int64
 1   Nome     5 non-null      object
 2   Regi√£o   5 non-null      object
 3   Cidade   5 non-null      object
 4   Tipo     5 non-null      object
dtypes: int64(1), object(4)
memory usage: 332.0+ bytes
None

 Tipos de dados:
Loja_ID     int64
Nome       object
Regi√£o     object
Cidade     object
Tipo       object
dtype: object

 Primeiras linhas:
   Loja_ID                     Nome    Regi√£o                Cidade    Tipo
0        1         Loja Borges S.A.    Centro                Leiria  Online
1        2          Loja Ramos Lda.   Algarve                 Lagoa  F√≠sica
2        3          Loja Ara√∫jo S/A  Alentejo  Ferreira do Alentejo  F√≠sica
3        4  Loja Maia Loureiro S.A.    Centro        Castelo Branco  F√≠sica
4        5   Loja Ara√∫jo Pinto Lda.    Centro      Castelo de Paiva  Online

 Valores nulos por coluna:
Loja_ID    0
Nome       0
Regi√£o     0
Cidade     0
Tipo       0
dtype: int64

 Strings vazias por coluna:
Loja_ID    0
Nome       0
Regi√£o     0
Cidade     0
Tipo       0
dtype: int64

 Registros duplicados: 0

 Valores √∫nicos por coluna:
Loja_ID    5
Nome       5
Regi√£o     3
Cidade     5
Tipo       2
dtype: int64

üìä Estat√≠sticas descritivas:
         Loja_ID              Nome  Regi√£o  Cidade    Tipo
count   5.000000                 5       5       5       5
unique       NaN                 5       3       5       2
top          NaN  Loja Borges S.A.  Centro  Leiria  F√≠sica
freq         NaN                 1       3       1       3
mean    3.000000               NaN     NaN     NaN     NaN
std     1.581139               NaN     NaN     NaN     NaN
min     1.000000               NaN     NaN     NaN     NaN
25%     2.000000               NaN     NaN     NaN     NaN
50%     3.000000               NaN     NaN     NaN     NaN
75%     4.000000               NaN     NaN     NaN     NaN
max     5.000000               NaN     NaN     NaN     NaN

==================================================
 Analisando: Produtos.csv
==================================================

 Info geral:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Produto_ID       1000 non-null   int64
 1   Nome             1000 non-null   object
 2   Categoria        1000 non-null   object
 3   Cor              1000 non-null   object
 4   Descri√ß√£o        1000 non-null   object
 5   Tamanho          1000 non-null   object
 6   Pre√ßo            1000 non-null   float64
 7   Custo_Aquisi√ß√£o  1000 non-null   float64
 8   Imagem           1000 non-null   object
dtypes: float64(2), int64(1), object(6)
memory usage: 70.4+ KB
None

 Tipos de dados:
Produto_ID           int64
Nome                object
Categoria           object
Cor                 object
Descri√ß√£o           object
Tamanho             object
Pre√ßo              float64
Custo_Aquisi√ß√£o    float64
Imagem              object
dtype: object

 Primeiras linhas:
   Produto_ID      Nome Categoria     Cor  \
0           1       Qui    Roupas   Verde
1           2        Id   Cal√ßado    Azul
2           3   Aliquam    Roupas   Preto
3           4      Iure   Cal√ßado   Verde
4           5  Deleniti    Roupas  Branco

                                           Descri√ß√£o Tamanho  Pre√ßo  \
0                  Doloribus dignissimos voluptatem.      XS  71.30
1  Id ratione expedita labore explicabo asperiore...      44  33.82
2              Culpa inventore eum eum impedit quos.      XS  78.52
3  Consequatur voluptatum ipsam expedita debitis ...      44  31.65
4       Omnis cum distinctio impedit illo hic ipsam.       M  74.78

   Custo_Aquisi√ß√£o                                        Imagem
0            17.39   https://source.unsplash.com/200x200/?roupas
1            39.87  https://source.unsplash.com/200x200/?cal√ßado
2            48.01   https://source.unsplash.com/200x200/?roupas
3            40.29  https://source.unsplash.com/200x200/?cal√ßado
4            10.63   https://source.unsplash.com/200x200/?roupas

 Valores nulos por coluna:
Produto_ID         0
Nome               0
Categoria          0
Cor                0
Descri√ß√£o          0
Tamanho            0
Pre√ßo              0
Custo_Aquisi√ß√£o    0
Imagem             0
dtype: int64

 Strings vazias por coluna:
Produto_ID         0
Nome               0
Categoria          0
Cor                0
Descri√ß√£o          0
Tamanho            0
Pre√ßo              0
Custo_Aquisi√ß√£o    0
Imagem             0
dtype: int64

 Registros duplicados: 0

 Valores √∫nicos por coluna:
Produto_ID         1000
Nome                182
Categoria             2
Cor                  10
Descri√ß√£o          1000
Tamanho              17
Pre√ßo               948
Custo_Aquisi√ß√£o     867
Imagem                2
dtype: int64

üìä Estat√≠sticas descritivas:
         Produto_ID  Nome Categoria       Cor  \
count   1000.000000  1000      1000      1000
unique          NaN   182         2        10
top             NaN  Modi   Cal√ßado  Vermelho
freq            NaN    15       501       112
mean     500.500000   NaN       NaN       NaN
std      288.819436   NaN       NaN       NaN
min        1.000000   NaN       NaN       NaN
25%      250.750000   NaN       NaN       NaN
50%      500.500000   NaN       NaN       NaN
75%      750.250000   NaN       NaN       NaN
max     1000.000000   NaN       NaN       NaN

                                                Descri√ß√£o Tamanho  \
count                                                1000    1000
unique                                               1000      17
top     Maiores dolor minus dolores laboriosam odit ip...      XS
freq                                                    1      94
mean                                                  NaN     NaN
std                                                   NaN     NaN
min                                                   NaN     NaN
25%                                                   NaN     NaN
50%                                                   NaN     NaN
75%                                                   NaN     NaN
max                                                   NaN     NaN

              Pre√ßo  Custo_Aquisi√ß√£o  \
count   1000.000000      1000.000000
unique          NaN              NaN
top             NaN              NaN
freq            NaN              NaN
mean      60.213670        30.211600
std       23.245781        11.596158
min       20.080000        10.020000
25%       40.182500        19.927500
50%       60.835000        30.560000
75%       80.052500        40.042500
max       99.920000        49.970000

                                              Imagem
count                                           1000
unique                                             2
top     https://source.unsplash.com/200x200/?cal√ßado
freq                                             501
mean                                             NaN
std                                              NaN
min                                              NaN
25%                                              NaN
50%                                              NaN
75%                                              NaN
max                                              NaN

In [21]:
df_historico_vendas = pd.read_csv(os.path.join(path, 'Historico_Vendas.csv'))
df_lojas = pd.read_csv(os.path.join(path, 'Lojas.csv'))
df_produtos = pd.read_csv(os.path.join(path, 'Produtos.csv'))

In [22]:
df_historico_vendas['Data da Venda'] = pd.to_datetime(df_historico_vendas['Data da Venda'])
df_historico_vendas.rename(columns={'Data da Venda': 'Data'}, inplace=True)
df_historico_vendas['Mes'] = df_historico_vendas['Data'].dt.month

In [23]:
df_produtos['Lucro Bruto'] = df_produtos['Pre√ßo'] - df_produtos['Custo_Aquisi√ß√£o']